export { default as featured } from './hubspot_translator_tile.svg'
export { default as one } from './dashboard.png'
export { default as two } from './cart.png'
export { default as three } from './onboarding-sketch.png'
export { default as four } from './hubspot-sketches1.jpg'
