export { default as featured } from './mmuf-white.jpg'
export { default as oneSm } from './mmuf-1-sm.jpg'
export { default as oneLg } from './mmuf-1-lg.jpg'
export { default as twoSm } from './mmuf-2-sm.jpg'
export { default as twoLg } from './mmuf-2-lg.png'
export { default as threeSm } from './mmuf-3-sm.png'
export { default as threeLg } from './mmuf-3-lg.png'
