export { default as featured } from './curriculum_tile.png'
export { default as oneSm } from './curriculum1-sm.jpg'
export { default as oneLg } from './curriculum1-lg.jpg'
export { default as twoSm } from './curriculum2-sm.jpg'
export { default as twoLg } from './curriculum2-lg.jpg'
export { default as threeSm } from './curriculum3-sm.jpg'
export { default as threeLg } from './curriculum3-lg.jpg'
