export { default as featured } from './winterlight-poster.jpg'
export { default as oneSm } from './winterlight-home-sm.jpg'
export { default as oneLg } from './winterlight-home-lg.jpg'
export { default as twoSm } from './winterlight-press-sm.jpg'
export { default as twoLg } from './winterlight-press-lg.jpg'
export { default as threeSm } from './winterlight-vincent-sm.jpg'
export { default as threeLg } from './winterlight-vincent-lg.jpg'
