export { default as featured } from './featured.jpg'
export { default as oneSm } from './one-sm.jpg'
export { default as oneLg } from './one-lg.jpg'
export { default as twoSm } from './two-sm.jpg'
export { default as twoLg } from './two-lg.jpg'
export { default as threeSm } from './three-sm.jpg'
export { default as threeLg } from './three-lg.jpg'
